# Generated by Django 5.2.4 on 2025-08-25 16:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("artworks", "0001_initial"),
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="artwork",
            name="artist",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="artworks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="artwork",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.category",
            ),
        ),
        migrations.AddField(
            model_name="artwork",
            name="tags",
            field=models.ManyToManyField(blank=True, to="core.tag"),
        ),
        migrations.AddField(
            model_name="artworkimage",
            name="artwork",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="artworks.artwork",
            ),
        ),
        migrations.AddField(
            model_name="artworklike",
            name="artwork",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="likes",
                to="artworks.artwork",
            ),
        ),
        migrations.AddField(
            model_name="artworklike",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="artworkview",
            name="artwork",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="artwork_views",
                to="artworks.artwork",
            ),
        ),
        migrations.AddField(
            model_name="artworkview",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="artwork",
            index=models.Index(
                fields=["availability", "is_published"],
                name="artworks_ar_availab_cb393a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="artwork",
            index=models.Index(
                fields=["artist", "availability"], name="artworks_ar_artist__7293e9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="artwork",
            index=models.Index(
                fields=["category", "availability"],
                name="artworks_ar_categor_2e724c_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="artworklike",
            unique_together={("user", "artwork")},
        ),
        migrations.AlterUniqueTogether(
            name="artworkview",
            unique_together={("user", "artwork", "ip_address")},
        ),
    ]
